FROM python:3
WORKDIR /opt/app
COPY app.py .
COPY requirements.txt .
RUN pip install -r requirements.txt --no-cache-dir -t ./dependencies
ENV PYTHONPATH=/opt/app/dependencies
CMD [ "python", "app.py"]